# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(873, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btProblemAdd = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemAdd.setFont(font)
        self.btProblemAdd.setObjectName("btProblemAdd")
        self.verticalLayout.addWidget(self.btProblemAdd)
        self.btProblemUpdate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemUpdate.setFont(font)
        self.btProblemUpdate.setObjectName("btProblemUpdate")
        self.verticalLayout.addWidget(self.btProblemUpdate)
        self.btProblemSave = QtWidgets.QPushButton(self.centralwidget)
        self.btProblemSave.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemSave.setFont(font)
        self.btProblemSave.setObjectName("btProblemSave")
        self.verticalLayout.addWidget(self.btProblemSave)
        self.btProblemCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btProblemCancel.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemCancel.setFont(font)
        self.btProblemCancel.setObjectName("btProblemCancel")
        self.verticalLayout.addWidget(self.btProblemCancel)
        self.btProblemDel = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemDel.setFont(font)
        self.btProblemDel.setObjectName("btProblemDel")
        self.verticalLayout.addWidget(self.btProblemDel)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.EditFind = QtWidgets.QLineEdit(self.centralwidget)
        self.EditFind.setObjectName("EditFind")
        self.verticalLayout.addWidget(self.EditFind)
        self.btProblemFind = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemFind.setFont(font)
        self.btProblemFind.setObjectName("btProblemFind")
        self.verticalLayout.addWidget(self.btProblemFind)
        self.btProblemReset = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btProblemReset.setFont(font)
        self.btProblemReset.setObjectName("btProblemReset")
        self.verticalLayout.addWidget(self.btProblemReset)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 873, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.user_action = QtWidgets.QAction(MainWindow)
        self.user_action.setObjectName("user_action")
        self.unit_action = QtWidgets.QAction(MainWindow)
        self.unit_action.setObjectName("unit_action")
        self.services_action = QtWidgets.QAction(MainWindow)
        self.services_action.setObjectName("services_action")
        self.menu.addAction(self.unit_action)
        self.menu.addAction(self.user_action)
        self.menu.addAction(self.services_action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Заявки на устранение не исправностей"))
        self.btProblemAdd.setText(_translate("MainWindow", "Добавить заявку"))
        self.btProblemUpdate.setText(_translate("MainWindow", "Обновить заявку"))
        self.btProblemSave.setText(_translate("MainWindow", "Сохранить изменения"))
        self.btProblemCancel.setText(_translate("MainWindow", "Отменить изменения"))
        self.btProblemDel.setText(_translate("MainWindow", "Удалить заявку"))
        self.label_2.setText(_translate("MainWindow", "Поиск по тексту заявки"))
        self.btProblemFind.setText(_translate("MainWindow", "Искать"))
        self.btProblemReset.setText(_translate("MainWindow", "Сбросить фильтр"))
        self.menu.setTitle(_translate("MainWindow", "Справочники"))
        self.user_action.setText(_translate("MainWindow", "Сотрудники"))
        self.unit_action.setText(_translate("MainWindow", "Подразделения"))
        self.services_action.setText(_translate("MainWindow", "Сервисные службы"))
