# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_user(object):
    def setupUi(self, Dialog_user):
        Dialog_user.setObjectName("Dialog_user")
        Dialog_user.resize(1027, 567)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_user)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableUser = QtWidgets.QTableWidget(Dialog_user)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableUser.setFont(font)
        self.tableUser.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableUser.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableUser.setRowCount(0)
        self.tableUser.setColumnCount(5)
        self.tableUser.setObjectName("tableUser")
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(4, item)
        self.tableUser.horizontalHeader().setSortIndicatorShown(True)
        self.tableUser.horizontalHeader().setStretchLastSection(True)
        self.tableUser.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.tableUser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btUserAdd = QtWidgets.QPushButton(Dialog_user)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserAdd.setFont(font)
        self.btUserAdd.setObjectName("btUserAdd")
        self.verticalLayout.addWidget(self.btUserAdd)
        self.btUserUpdate = QtWidgets.QPushButton(Dialog_user)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserUpdate.setFont(font)
        self.btUserUpdate.setObjectName("btUserUpdate")
        self.verticalLayout.addWidget(self.btUserUpdate)
        self.btUserDel = QtWidgets.QPushButton(Dialog_user)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserDel.setFont(font)
        self.btUserDel.setObjectName("btUserDel")
        self.verticalLayout.addWidget(self.btUserDel)
        self.label = QtWidgets.QLabel(Dialog_user)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog_user)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_user)
        QtCore.QMetaObject.connectSlotsByName(Dialog_user)

    def retranslateUi(self, Dialog_user):
        _translate = QtCore.QCoreApplication.translate
        Dialog_user.setWindowTitle(_translate("Dialog_user", "Справочник сотрудников"))
        item = self.tableUser.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_user", "Таб. №"))
        item = self.tableUser.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_user", "ФИО"))
        item = self.tableUser.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_user", "Дата рождения"))
        item = self.tableUser.horizontalHeaderItem(3)
        item.setText(_translate("Dialog_user", "Пол"))
        item = self.tableUser.horizontalHeaderItem(4)
        item.setText(_translate("Dialog_user", "Подразделение"))
        self.btUserAdd.setText(_translate("Dialog_user", "Добавить строку ..."))
        self.btUserUpdate.setText(_translate("Dialog_user", "Обновить строку ..."))
        self.btUserDel.setText(_translate("Dialog_user", "Удалить строку ..."))
        self.label.setText(_translate("Dialog_user", "Поиск:"))

