# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_new.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_user_new(object):
    def setupUi(self, Dialog_user_new):
        Dialog_user_new.setObjectName("Dialog_user_new")
        Dialog_user_new.resize(527, 255)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_user_new)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, 10, 5, -1)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog_user_new)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.Edit_Fio = QtWidgets.QLineEdit(Dialog_user_new)
        self.Edit_Fio.setObjectName("Edit_Fio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.Edit_Fio)
        self.label_2 = QtWidgets.QLabel(Dialog_user_new)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.Edit_date = QtWidgets.QDateEdit(Dialog_user_new)
        self.Edit_date.setObjectName("Edit_date")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.Edit_date)
        self.label_3 = QtWidgets.QLabel(Dialog_user_new)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chB_male = QtWidgets.QCheckBox(Dialog_user_new)
        self.chB_male.setObjectName("chB_male")
        self.btnGr_s = QtWidgets.QButtonGroup(Dialog_user_new)
        self.btnGr_s.setObjectName("btnGr_s")
        self.btnGr_s.addButton(self.chB_male)
        self.horizontalLayout_2.addWidget(self.chB_male)
        self.chB_female = QtWidgets.QCheckBox(Dialog_user_new)
        self.chB_female.setObjectName("chB_female")
        self.btnGr_s.addButton(self.chB_female)
        self.horizontalLayout_2.addWidget(self.chB_female)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_4 = QtWidgets.QLabel(Dialog_user_new)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.CB_unit = QtWidgets.QComboBox(Dialog_user_new)
        self.CB_unit.setObjectName("CB_unit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.CB_unit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.btnUser_Ok = QtWidgets.QPushButton(Dialog_user_new)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnUser_Ok.setFont(font)
        self.btnUser_Ok.setObjectName("btnUser_Ok")
        self.horizontalLayout_6.addWidget(self.btnUser_Ok)
        self.btnUser_Cancel = QtWidgets.QPushButton(Dialog_user_new)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnUser_Cancel.setFont(font)
        self.btnUser_Cancel.setObjectName("btnUser_Cancel")
        self.horizontalLayout_6.addWidget(self.btnUser_Cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Dialog_user_new)
        QtCore.QMetaObject.connectSlotsByName(Dialog_user_new)

    def retranslateUi(self, Dialog_user_new):
        _translate = QtCore.QCoreApplication.translate
        Dialog_user_new.setWindowTitle(_translate("Dialog_user_new", "Dialog"))
        self.label.setText(_translate("Dialog_user_new", "ФИО"))
        self.label_2.setText(_translate("Dialog_user_new", "Дата рождения"))
        self.label_3.setText(_translate("Dialog_user_new", "Пол"))
        self.chB_male.setText(_translate("Dialog_user_new", "мужской"))
        self.chB_female.setText(_translate("Dialog_user_new", "женский"))
        self.label_4.setText(_translate("Dialog_user_new", "Подразделение"))
        self.btnUser_Ok.setText(_translate("Dialog_user_new", "Записать"))
        self.btnUser_Cancel.setText(_translate("Dialog_user_new", "Отмена"))

