# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(924, 515)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableUser = QtWidgets.QTableWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.tableUser.setFont(font)
        self.tableUser.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableUser.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableUser.setRowCount(0)
        self.tableUser.setColumnCount(5)
        self.tableUser.setObjectName("tableUser")
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableUser.setHorizontalHeaderItem(4, item)
        self.tableUser.horizontalHeader().setSortIndicatorShown(True)
        self.tableUser.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout.addWidget(self.tableUser)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btUserAdd = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserAdd.setFont(font)
        self.btUserAdd.setObjectName("btUserAdd")
        self.verticalLayout.addWidget(self.btUserAdd)
        self.btUserUpdate = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserUpdate.setFont(font)
        self.btUserUpdate.setObjectName("btUserUpdate")
        self.verticalLayout.addWidget(self.btUserUpdate)
        self.btUsersDel = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUsersDel.setFont(font)
        self.btUsersDel.setObjectName("btUsersDel")
        self.verticalLayout.addWidget(self.btUsersDel)
        self.btUserFind = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btUserFind.setFont(font)
        self.btUserFind.setObjectName("btUserFind")
        self.verticalLayout.addWidget(self.btUserFind)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableUser.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Таб. №"))
        item = self.tableUser.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ФИО"))
        item = self.tableUser.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Дата рождения"))
        item = self.tableUser.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Пол"))
        item = self.tableUser.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Подразделение"))
        self.btUserAdd.setText(_translate("Dialog", "Добавить строку ..."))
        self.btUserUpdate.setText(_translate("Dialog", "Обновить строку ..."))
        self.btUsersDel.setText(_translate("Dialog", "Удалить строку ..."))
        self.btUserFind.setText(_translate("Dialog", "Поиск ..."))

